IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'COMMANDE'))
BEGIN
	CREATE TABLE [dbo].[COMMANDE](
		[Id] bigint IDENTITY(1,1) NOT NULL,
	    [numCommande] bigint  NULL,
	    [dateCOMMANDE] datetime  NULL,
	    [etat] nvarchar(max)  NULL,
	    [RECEPTIONId] bigint  NOT NULL,
	    [FOURNISSEURId] bigint  NOT NULL		
	 CONSTRAINT [PK_COMMANDE] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 
END
GO
