IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'LIGNE_COMMANDE'))
BEGIN
	CREATE TABLE [dbo].[LIGNE_COMMANDE](
		[Id] bigint IDENTITY(1,1) NOT NULL,
	    [index] bigint  NULL,
	    [quantite] bigint  NULL,
	    [prix] bigint  NULL,
	    [montant] float  NULL,
	    [ARTICLEId] bigint  NOT NULL,
	    [COMMANDEId] bigint  NOT NULL		
	 CONSTRAINT [PK_LIGNE_COMMANDE] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 
END
GO
