IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'RECEPTION'))
BEGIN
	CREATE TABLE [dbo].[RECEPTION](
		[Id] bigint IDENTITY(1,1) NOT NULL,
	    [numReception] bigint  NULL,
	    [dateReception] datetime  NULL,
	    [quantiteLivree] bigint  NULL
	 CONSTRAINT [PK_RECEPTION] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 
END
GO
