//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICLE()
        {
            this.ENTREE = new HashSet<ENTREE>();
            this.SORTIE = new HashSet<SORTIE>();
            this.LIGNE_COMMANDE = new HashSet<LIGNE_COMMANDE>();
        }
    
        public long Id { get; set; }
        public string designation { get; set; }
        public string unit { get; set; }
        public Nullable<long> quantite { get; set; }
        public Nullable<long> prix { get; set; }
        public Nullable<long> newAttr { get; set; }
        public string emplacement { get; set; }
        public long CATEGORIE_ARTId { get; set; }
        public long FOURNISSEURId { get; set; }
        public long MAGASINId { get; set; }
    
        public virtual CATEGORIE_ART CATEGORIE_ART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTREE> ENTREE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORTIE> SORTIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNE_COMMANDE> LIGNE_COMMANDE { get; set; }
        public virtual FOURNISSEUR FOURNISSEUR { get; set; }
        public virtual MAGASIN MAGASIN { get; set; }
    }
}
