//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOURNISSEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOURNISSEUR()
        {
            this.COMMANDE = new HashSet<COMMANDE>();
            this.ARTICLE = new HashSet<ARTICLE>();
        }
    
        public long Id { get; set; }
        public long numF { get; set; }
        public string NomF { get; set; }
        public string adresse { get; set; }
        public Nullable<int> codP { get; set; }
        public string ville { get; set; }
        public string payes { get; set; }
        public Nullable<long> tele { get; set; }
        public Nullable<long> fax { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE> COMMANDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICLE> ARTICLE { get; set; }
    }
}
