//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIGNE_COMMANDE
    {
        public long Id { get; set; }
        public Nullable<long> index { get; set; }
        public Nullable<long> quantite { get; set; }
        public Nullable<long> prix { get; set; }
        public Nullable<double> montant { get; set; }
        public long ARTICLEId { get; set; }
        public long COMMANDEId { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual COMMANDE COMMANDE { get; set; }
    }
}
