//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SORTIE
    {
        public long Id { get; set; }
        public Nullable<long> numSortie { get; set; }
        public Nullable<long> quantite { get; set; }
        public Nullable<System.DateTime> dateSortie { get; set; }
        public Nullable<long> prixDSortie { get; set; }
        public long ARTICLEId { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
    }
}
