//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public string Id { get; set; }
        public string designation { get; set; }
        public string marque { get; set; }
        public string type { get; set; }
        public string quantite { get; set; }
        public string codeFournisseur { get; set; }
        public string fournisseur { get; set; }
        public string prixAchat { get; set; }
    }
}
