//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using Microsoft.AspNetCore.Identity;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class user : IdentityUser
    {
        [Column(TypeName = "int")]
        public int role { get; set; }

        [Column(TypeName = "VARCHAR(50)")]
        public string roleLabel { get; set; }

        [Column(TypeName = "VARCHAR(100)")]
        public string FullName { get; set; }

        public string Image { get; set; }
    }
}
