IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'AGENCE'))
BEGIN
	CREATE TABLE [dbo].[AGENCE](
		[Id] bigint  NOT NULL,
	    [nom] nvarchar(max) NULL,
	    [ville] nvarchar(100)  NULL,
	    [adresse] nvarchar(200)  NULL,
	    [telephone] nvarchar(50)  NULL,
	 CONSTRAINT [PK_AGENCE] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
