IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'CATEGORIE_ART'))
BEGIN
	CREATE TABLE [dbo].[CATEGORIE_ART](
		[Id] bigint  NOT NULL,
	    [nomCate] nvarchar(max)  NULL,
	    [description] nvarchar(max)  NULL
	 CONSTRAINT [PK_CATEGORIE_ART] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
