IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'COMMANDE'))
BEGIN
	CREATE TABLE [dbo].[COMMANDE](
		[Id] [BIGINT] NOT NULL,
		[numCommande] [BIGINT] NULL,
		[dateCOMMANDE] [DATETIME] NULL,
		[etat] [nvarchar](max) NULL,
		[IdFornisseur] [BIGINT] NOT NULL,
		[IdReception] [BIGINT] NOT NULL		
	 CONSTRAINT [PK_COMMANDE] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 
END
GO
