IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'ENTREE'))
BEGIN
	CREATE TABLE [dbo].[ENTREE](
		[Id] bigint  NOT NULL,
	    [numEntree] bigint  NULL,
	    [quantite] bigint  NULL,
	    [dateEntree] datetime  NULL,
	    [prixDentree] bigint  NULL,
	    [ARTICLEId] bigint  NOT NULL
	 CONSTRAINT [PK_ENTREE] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
