IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'LIGNE_COMMANDE'))
BEGIN
	CREATE TABLE [dbo].[LIGNE_COMMANDE](
		[Id] [BIGINT] NOT NULL,
		[index] [BIGINT] NULL,
		[quantite] [BIGINT] NULL,
		[prix] [BIGINT] NULL,
		[montant] [FLOAT] NULL,
		[IdArticle] [BIGINT] NOT NULL,
		[IdCommande] [BIGINT] NOT NULL		
	 CONSTRAINT [PK_LIGNE_COMMANDE] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 
END
GO
