IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'RECEPTION'))
BEGIN
	CREATE TABLE [dbo].[RECEPTION](
		[Id] [BIGINT] NOT NULL,
		[numReception] [BIGINT] NULL,
		[dateReception] [DATETIME] NULL,
		[quantiteLivree] [BIGINT] NULL
	 CONSTRAINT [PK_RECEPTION] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 
END
GO
