IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'SORTIE'))
BEGIN
	CREATE TABLE [dbo].[SORTIE](
		[Id] [BIGINT] NOT NULL,
		[numSortie] [BIGINT] NULL,
		[quantite] [BIGINT] NULL,
		[dateSortie] [DATETIME] NULL,
		[prixDSortie] [BIGINT] NULL,
		[IdArticle] [BIGINT] NOT NULL
	 CONSTRAINT [PK_SORTIE] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
