IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'SORTIE'))
BEGIN
	CREATE TABLE [dbo].[SORTIE](
		[Id] bigint  NOT NULL,
	    [numSortie] bigint  NULL,
	    [quantite] bigint  NULL,
	    [dateSortie] datetime  NULL,
	    [prixDSortie] bigint  NULL,
	    [ARTICLEId] bigint  NOT NULL
	 CONSTRAINT [PK_SORTIE] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
