//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCE
    {
        public long Id { get; set; }
        public string nom { get; set; }
        public string ville { get; set; }
        public string adresse { get; set; }
        public string telephone { get; set; }
    }
}
