//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMANDE()
        {
            this.LIGNE_COMMANDE = new HashSet<LIGNE_COMMANDE>();
            this.RECEPTION = new HashSet<RECEPTION>();
        }
    
        public long Id { get; set; }
        public Nullable<long> numCommande { get; set; }
        public Nullable<System.DateTime> dateCOMMANDE { get; set; }
        public string etat { get; set; }
        public long FOURNISSEURId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNE_COMMANDE> LIGNE_COMMANDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPTION> RECEPTION { get; set; }
        public virtual FOURNISSEUR FOURNISSEUR { get; set; }
    }
}
