//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess.Models
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("LIGNE_COMMANDE")]
    public partial class LIGNE_COMMANDE
    {
        public long Id { get; set; }
        public Nullable<long> index { get; set; }
        public Nullable<long> quantite { get; set; }
        public Nullable<long> prix { get; set; }
        public Nullable<double> montant { get; set; }
        public long ARTICLEId { get; set; }
        public long COMMANDEId { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual COMMANDE COMMANDE { get; set; }
    }
}
