//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SORTIE
    {
        public long Id { get; set; }
        public Nullable<long> numSortie { get; set; }
        public Nullable<long> quantite { get; set; }
        public Nullable<System.DateTime> dateSortie { get; set; }
        public Nullable<long> prixDSortie { get; set; }
        public long ARTICLEId { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
    }
}
