//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUS_TRAITANT
    {
        public long Id { get; set; }
        public string nom { get; set; }
        public string ville { get; set; }
        public string adresse { get; set; }
        public string telephone { get; set; }
    }
}
