//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess.Models
{
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SOUS_TRAITANT")]
    public partial class SOUS_TRAITANT
    {
        public long Id { get; set; }
        public string nom { get; set; }
        public string ville { get; set; }
        public string adresse { get; set; }
        public string telephone { get; set; }
    }
}
