//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess.Models
{
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("STOCK")]
    public partial class STOCK
    {
        public string Id { get; set; }
        public string designation { get; set; }
        public string marque { get; set; }
        public string type { get; set; }
        public string quantite { get; set; }
        public string codeFournisseur { get; set; }
        public string fournisseur { get; set; }
        public string prixAchat { get; set; }
    }
}
